# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae942218e8abca62084e3ba68f8aff07603aa2acb814fb3dd8c4a0e28b18fbc8f7c111375b44e01e6177bfe0293c15786a0b275fc009caa55391589d58602cfc

test:
  secret_key_base: 439ba7f4522b162cd71d6f69f5a27b011e1b2fc4756e74ee77c1022827e8ded3d2141d2fd883a8d9dac274290d6a02eb1896334ef8430b70bd4d4b2f7be0edd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
